# frozen_string_literal: true

source 'https://rubygems.org'

group :test do
  gem 'rspec'
  gem 'rspec-parameterized'
end

# For plain Ruby scripts
group :development do
  gem 'rubocop-fjord', require: false
end
